spring:
  cloud:
    zookeeper:
      discovery:
        enabled: true  # 使用zookeeper作为注册中心
        register: true  # 使用zookeeper作为注册中心
        preferIpAddress: true  # 设置为true是使用ip地址，false是计算机名
      connect-string: hadoop01:2181,hadoop02:2181,hadoop03:2181
  application:
    name: cloud_e2e

server:
  port: 0 # 0表示随机端口